### ISSUE TITLE
How can I make other servers log in at the same time?

### ISSUE THREAD

**Issue by sekaom** [4drian3d/AuthMeVelocity#100]
I switched from BungeeCord to Velocity. I installed the corresponding plug-in on the server and proxy server Velocity according to the tutorial, but I still have a problem that has not been solved: automatically log in to other sub-servers, or synchronise the login status. The configuration file in authmebungee is "autoLogin"   
  
  
The following are my authmevelocity settings and Velocity's server settings

![0FADFE59-E24F-403F-ACE6-CB86FDCD199E](https://github.com/4drian3d/AuthMeVelocity/assets/90206655/a2dd5e2b-6297-4f9b-92c9-5b1ef61fc400)
![D99CF7CC-483C-4451-89E4-163793B0DB51](https://github.com/4drian3d/AuthMeVelocity/assets/90206655/158bc147-ced4-4639-974b-6388280c3217)

**Comment by shubham8550** [comment]
maybe Enable the Hooks.bungeecord option in your AuthMeReloaded config file

**Comment by 4drian3d** [comment]
> maybe Enable the Hooks.bungeecord option in your AuthMeReloaded config file

AuthMeReloaded has bugs with that function, that's why I implemented it in AuthMeVelocity but recently a bug was fixed that didn't allow it to work, in a few hours I will release a new release fixing this

**Comment by 4drian3d** [comment]
Fixed in https://hangar.papermc.io/4drian3d/AuthMeVelocity/versions/4.0.2

**Comment by shubham8550** [comment]
> maybe Enable the Hooks.bungeecord option in your AuthMeReloaded config file

this didn't work for me so i enabled session 

to make it work
