### ISSUE TITLE
If players is not logged in, they will be kicked when using/server

### ISSUE THREAD

**Issue by 2032382213** [4drian3d/AuthMeVelocity#110]
My Velocity version is 3.2.0-SNAPSHOT (git-37fedf50-b260). When players use "/server", Velocity will report an error of "A plugin tried to deny a command with signed component (s). This is not supported. Disconnecting player XXX"

**Comment by 4drian3d** [comment]
Install https://modrinth.com/plugin/signedvelocity or https://modrinth.com/plugin/unsignedvelocity

**Comment by 4drian3d** [comment]
#48

**Comment by Troughy** [comment]
> Install https://modrinth.com/plugin/signedvelocity or https://modrinth.com/plugin/unsignedvelocity

would you mind adding this to README.md? I think every single server owner/admin is going test if blocking commands (especially commands like /server) work, so it's important enough for them to see before having to look through issues on github

**Comment by 4drian3d** [comment]
> > Install https://modrinth.com/plugin/signedvelocity or https://modrinth.com/plugin/unsignedvelocity
> 
> would you mind adding this to README.md? I think every single server owner/admin is going test if blocking commands (especially commands like /server) work, so it's important enough for them to see before having to look through issues on github
> 
> EDIT: By the way, after installing SignedVelocity, I don't get kicked for running commands, but commands are not blocked. ![click here](https://camo.githubusercontent.com/541ecc566a209ab1dcf80afe671d8467aa96b030163accc3d22a266712d8cafa/68747470733a2f2f692e696d6775722e636f6d2f7651794245354d2e706e67) (however, running /server lobby does nothing, so I guess it kinda works?) edit again: UnsignedVelocity works perfectly fine! commands are blocked as intended, so I guess I'll be using that

That only happens if you have not followed the SignedVelocity installation guide in its README, I would recommend you to use SignedVelocity instead of UnSignedVelocity

**Comment by Troughy** [comment]
> > > Install https://modrinth.com/plugin/signedvelocity or https://modrinth.com/plugin/unsignedvelocity
> > 
> > 
> > would you mind adding this to README.md? I think every single server owner/admin is going test if blocking commands (especially commands like /server) work, so it's important enough for them to see before having to look through issues on github
> > EDIT: By the way, after installing SignedVelocity, I don't get kicked for running commands, but commands are not blocked. ![click here](https://camo.githubusercontent.com/541ecc566a209ab1dcf80afe671d8467aa96b030163accc3d22a266712d8cafa/68747470733a2f2f692e696d6775722e636f6d2f7651794245354d2e706e67) (however, running /server lobby does nothing, so I guess it kinda works?) edit again: UnsignedVelocity works perfectly fine! commands are blocked as intended, so I guess I'll be using that
> 
> That only happens if you have not followed the SignedVelocity installation guide in its README, I would recommend you to use SignedVelocity instead of UnSignedVelocity

Not true, I followed the installation guide, installing both the proxy and the server jars to the correct places.. Must be a bug with SignedVelocity then. https://streamable.com/42za4u (after the cut you can see in the console logs that the plugin loaded)
