### ISSUE TITLE
[ENHANCEMENT] Compatibility with Remember Me

### ISSUE THREAD

**Issue by QuartzWarrior** [4drian3d/AuthMeVelocity#113]
Add compatibility with the [Remember Me](https://github.com/ActualPlayer/RememberMe) plugin for velocity. (Solution to #112 )

**Comment by RealTriassic** [comment]
Isn't this similar? https://github.com/4drian3d/AuthMeVelocity-LastServerAddon

**Comment by QuartzWarrior** [comment]
Oh snap, it is, thanks
