### ISSUE TITLE
Can't join to the server

### ISSUE THREAD

**Issue by F3F5** [4drian3d/AuthMeVelocity#127]
After Velocity added 1.20.2 support, plugin not working cause API changes

**Comment by 4drian3d** [comment]
What do you mean the API has changed? And what is the error that is not allowing you to enter? Can you give more information?

**Comment by F3F5** [comment]
> What do you mean the API has changed? And what is the error that is not allowing you to enter? Can you give more information?

it simple 'disconnect' without errors.
plugin limboapi has the same issues, but fixed

**Comment by 4drian3d** [comment]
There is no information that the error is caused by AuthMeVelocity

**Comment by F3F5** [comment]
> There is no information that the error is caused by AuthMeVelocity

you maybe test? well, bye
