### ISSUE TITLE
Failed to register events for class io.github._4drian3d.authmevelocity.paper.listeners.AuthMeListener

### ISSUE THREAD

**Issue by AnghiYt** [4drian3d/AuthMeVelocity#139]
After updating the plugin to the latest version (4.1) I can't log in to the server. I manage to enter the server and after logging in with authme, trying to execute the commands I get the error message that I am not logged in. This message appears on the authentication server:

[AuthMeVelocity] Failed to register events for class io.github._4drian3d.authmevelocity.paper.listeners.AuthMeListener because fr/xephi/authme/events/RegisterEvent does not exist.

**Comment by 4drian3d** [comment]
What version of AuthMeReloaded are you trying to use? That event has been around for more than 5 years

**Comment by AnghiYt** [comment]
5.6 build 2614

**Comment by 4drian3d** [comment]
I tested that specific build and could not reproduce the bug
