### ISSUE TITLE
BUG - Players dont take damage after switching servers

### ISSUE THREAD

**Issue by CursedHawk420** [4drian3d/AuthMeVelocity#142]
Servers version:
 - Paper 1.20.1-196

AuthMeVelocity version: 
 - both paper and velocity - 4.1.0 (4.0.4 too)

Authme version: 
 - Fork you mentioned on github page
 - any other version i tried  

SETUP: 
 - All servers are auth servers

Problem scenario: 
When running all servers as auth servers, switching between them logs in players correctly. 
But when they switch server A to server B, they stop taking damage. PVP, PVE, but fall damage sometimes works. 
Please help us out.

**Comment by 4drian3d** [comment]
This definitely has nothing to do with this project

**Comment by CursedHawk420** [comment]
Okay, what's the problem please?
