### ISSUE TITLE
Not compatible with latest version of Velocity 3.3.0-b329+

### ISSUE THREAD

**Issue by Athar42** [4drian3d/AuthMeVelocity#144]
Opening the issue there, same as SignedVelocity : https://github.com/4drian3d/SignedVelocity/issues/70

Issue since changes made on Velocity proxy build 329.

> [14:12:11 ERROR]: Couldn't pass ProxyInitializeEvent to authmevelocity
> java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/TabCompleteResponse
>         at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
>         at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
>         at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
>         at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:816) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:735) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:431) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:177) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:686) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:629) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:615) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:990) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:902) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:302) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:225) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1140) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1169) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1134) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at io.github._4drian3d.authmevelocity.velocity.AuthMeVelocityPlugin.onProxyInitialization(AuthMeVelocityPlugin.java:161) ~[?:?]
>         at io.github._4drian3d.authmevelocity.velocity.Lmbda$7.execute(Unknown Source) ~[?:?]
>         at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.TabCompleteResponse
>         at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
>         ... 27 more
> [14:12:11 INFO] [signedvelocity]: Starting SignedVelocity

Thanks <3

**Comment by 4drian3d** [comment]
Fixed in the latest version
