### ISSUE TITLE
[Feature requests] bypass sending premium account to the authentication server

### ISSUE THREAD

**Issue by moesnow** [4drian3d/AuthMeVelocity#149]
If a player has a premium account (via FastLogin), is it possible to bypass sending them to the authentication server and instead directly teleport them to another server?

**Comment by 4drian3d** [comment]
I would recommend you to use another plugin like LibreLogin to do this, AuthMeVelocity is a plugin that depends on AuthMeReloaded to work, so it requires AuthMeReloaded to tell it that a player is logged in to send it to some other server
