### ISSUE TITLE
Suggestion to the modrinth page

### ISSUE THREAD

**Issue by XSzolX** [4drian3d/AuthMeVelocity#161]
Suggestion to the Setup section. At the beginning add "Download AuthMeReloaded on all of your backend servers". I had some issues with that. I had to watch the tutorial in spanish to realise why the plugin wasn't working for me. Turns out I need AuthMeReloaded itself too.

You can also make a text saying to install FastLogin on the backend servers not the proxy.

**Please consider** it as I think it would improve the page.

**[NOT URGENT]**

**Comment by 4drian3d** [comment]
> Turns out I need AuthMeReloaded itself too.

I will add it, I never thought there would be someone who would think they could use an add-on to a plugin without the main plugin

> Download AuthMeReloaded on all of your backend servers

Definitely not necessary or recommended, but possible and supported

>  install FastLogin on the backend servers not the proxy

https://github.com/games647/FastLogin?tab=readme-ov-file#bungeecordwaterfall-or-velocity
