### ISSUE TITLE
Issue with command whitelist when you're not logged in

### ISSUE THREAD

**Issue by Innesity** [4drian3d/AuthMeVelocity#163]
Hello. It looks like authmevelocity have some issues not restricting players to use any other commands (on velocity level) than the one granted in authmevelocity (in velocity's config) 
![image](https://github.com/4drian3d/AuthMeVelocity/assets/59732057/50865971-6fb4-4ea3-ac29-64288cceb44b)
I've tried to add SignedVelocity (on both paper and velocity servers) and VPacketEvents(on velocity), but this is still happening

Authme, paper, velocity, authmevelocity versions: 
![image](https://github.com/4drian3d/AuthMeVelocity/assets/59732057/fd482343-3ec8-4dd7-a809-a6f74d121b6d)

**Comment by 4drian3d** [comment]
That seems to be a clear problem with the plugin you use for the chat in Velocity, chat plugins should never use the priority https://jd.papermc.io/velocity/3.3.0/com/velocitypowered/api/event/PostOrder.html#FIRST and should always check if the event has already been cancelled
