### ISSUE TITLE
[BUG] The plugin don't automatically login when switching to auth-server - gameserver

### ISSUE THREAD

**Issue by ftita** [4drian3d/AuthMeVelocity#30]
Hi, 
I'm trying to use this plugin for my server (100-200on) and I have the problem that this plugin works really fine, but, it dosen't automatically login when switching to auth-server - gameserver. (Sorry for my bad english, I'm Italian)

**Comment by ImFound** [comment]
same problem

**Comment by 4drian3d** [comment]
Actually you only need to install Authme only on your Auth server. But in a short moment I will add support for some setups that have only one auth/lobby server (funny that I haven't support it yet since my own server works like that xD) or that have authme on all servers (not recommended)

**Comment by aglarcz** [comment]
Still not working on one lobby/auth server - after loggin in player is ported again to the same lobby and needs to login again. Can something be done about it please?

**Comment by 4drian3d** [comment]
> Still not working with one lobby/auth server setup - after logging in player is ported again to the same lobby and needs to login again. Can something be done about it please?
> 
> (used compiled version from current source)

Could you try the last commit?

**Comment by 4drian3d** [comment]
As of version 2.2.0 this function should be implemented, although I have no server available to test it and no one has confirmed its correct operation https://github.com/4drian3d/AuthMeVelocity/releases/tag/2.2.0
