### ISSUE TITLE
[Bug] Can't enter the server

### ISSUE THREAD

**Issue by steveminecraft2** [4drian3d/AuthMeVelocity#44]
When I updated the plugin it can't connect to the server all the time. It keeps writing: "Joining world" and then in the console: "read timed out"

**Comment by 4drian3d** [comment]
Could you test if this build fixes the bug https://github.com/4drian3d/AuthMeVelocity/suites/7564233769/artifacts/312549672 ?

**Comment by steveminecraft2** [comment]
not working on my server

> Could you test if this build fixes the bug https://github.com/4drian3d/AuthMeVelocity/suites/7564233769/artifacts/312549672 ?

**Comment by 4drian3d** [comment]
Does it work with the previous release of AuthmeVelocity or without AuthmeVelocity installed?

**Comment by steveminecraft2** [comment]
without authmevelocity works. Version [2.1.1] works 

> Does it work with the previous release of AuthmeVelocity or without AuthmeVelocity installed?

**Comment by steveminecraft2** [comment]
I updated and it still doesn't connect to server 1.19 at all

**Comment by 4drian3d** [comment]
Yes... I just saw the bug, now I fix it and release another release

**Comment by 4drian3d** [comment]
https://github.com/4drian3d/AuthMeVelocity/releases/tag/2.2.2

**Comment by steveminecraft2** [comment]
it works!
