### ISSUE TITLE
Velocity 3.1.2 - 167 Build Bug - 

### ISSUE THREAD

**Issue by Imptovskii** [4drian3d/AuthMeVelocity#46]
Hello!

I have such a problem, with the plugin installed, I don’t have any switches to other servers, even through the server command it doesn’t switch, I forgot to record it on video. Everything is fine without the plugin.

https://www.youtube.com/watch?v=dC_QTHSBw94

**Comment by 4drian3d** [comment]
It is not clear in the video but do you have AuthmeVelocity-spigot installed on the server?

**Comment by Imptovskii** [comment]
> It is not clear in the video but do you have AuthmeVelocity-spigot installed on the server?

Yes. AuthmeVelocity-spigot installed on the server. the problem appeared recently, after the release of 1.19.1

**Comment by 4drian3d** [comment]
The only possibilities for this to happen is that you do not have AuthmeVelocity-Spigot installed, that some plugin cancels the `PreSendLoginEvent` event or that some plugin for some reason is modifying the user name directly instead of its displayname

**Comment by AnghiYt** [comment]
I have the same problem with velocity 3.1.2 - 171. I upgraded the plugin from version 2.1.1 to 2.2.2 and it stopped working. I specify that I have only updated the version of this plugin. The other plugins remained the same

**Comment by Mowstyl** [comment]
I also have the same problem. I can only connect to the servers on the authServers list.

**Comment by 4drian3d** [comment]
Can anyone test this version https://github.com/4drian3d/AuthMeVelocity/actions/runs/2852201732 ?

**Comment by AnghiYt** [comment]
Yeah. Now it works
