### ISSUE TITLE
Illegal protocol state

### ISSUE THREAD

**Issue by Mowstyl** [4drian3d/AuthMeVelocity#48]
Greetings.
I was testing if the plugin was preventing players from executing commands (like /server) or sending messages and, while they can't do it, they get kicked.
The kick message is "A proxy plugin caused an illegal protocol state. Contact your network administrator.".
I have the last version of your -spigot plugin on the auth server and a version of the -proxy plugin I've just compiled from your source only having changed what I said on my message in [Velocity 3.1.2 - 167 Build Bug - #46](https://github.com/4drian3d/AuthMeVelocity/issues/46) (otherwise players won't be able to exit the auth server).

I'm using velocity-3.1.2-SNAPSHOT-172 and paper-1.19.2-125.jar.

If you need any extra information, please feel free to ask, and congratulations for this incredible plugin, if it didn't exist I'd still using other proxies rather than velocity!

**Comment by 4drian3d** [comment]
The error is because the player you want to deny the execution of the command is using a Minecraft client 1.19.1 or higher and has a valid signed key. Currently Velocity kicks the player in case some plugin denies or modifies some of his messages. I can't do anything to fix it other than to avoid cancelling the message on such players

**Comment by Mowstyl** [comment]
Ok, 1.19.1 is really giving headaches to everyone...
Thank you for your quick reply!

**Comment by 4drian3d** [comment]
For those who have this problem, you can use my plugin UnSignedVelocity https://modrinth.com/plugin/unsignedvelocity so that AuthMeVelocity can block chat commands and messages until users register/log in to the server
