### ISSUE TITLE
1.19.2 or 1.19.3 doesnt work!

### ISSUE THREAD

**Issue by EndermanPvP** [4drian3d/AuthMeVelocity#65]

**Comment by 4drian3d** [comment]
What?

**Comment by EndermanPvP** [comment]
This isn’t invalid this plugin does not work on 1.19.3. Not sure how you do not understand this as you are a “developer”

**Comment by EndermanPvP** [comment]
Seems silly to close a valid ticket buddy

**Comment by 4drian3d** [comment]
> Seems silly to close a valid ticket buddy
The only thing you have said is "1.19.2 or 1.19.3 doesnt work" without any explanation or description as to what the possible fault might be

**Comment by yusshu** [comment]
![image](https://user-images.githubusercontent.com/45738853/209041021-2aaa5868-8000-418e-946d-9f7bbf3f3f8b.png)

**Comment by EndermanPvP** [comment]
You can see the whole explanation in the title.

**Comment by Pabszito** [comment]
> You can see the whole explanation in the title.

Is it that hard to provide a stack trace though?

**Comment by 4drian3d** [comment]
![authmev](https://user-images.githubusercontent.com/68704415/209240559-24f8db6b-9059-4e6d-8fd3-b90fddd39367.png)
AuthMeVelocity starts correctly in the latest Paper 1.19.3 build, I will close this issue due to lack of information

**Comment by EndermanPvP** [comment]
Doesn’t connect with Auth me bungee config, and commands kick you. Maybe if you tried using your mind you would know

**Comment by 4drian3d** [comment]
> Doesn’t connect with Auth me bungee config, and commands kick you. Maybe if you tried using your mind you would know

This plugin has nothing to do with AuthMeBungee, neither share configuration, not even the configuration format since AuthMeBungee uses YAML and AuthMeVelocity uses HOCON

About the kick, there is a specific option in the configuration to configure this section.

**Comment by 4drian3d** [comment]
This type of questions could be quickly solved on the support discord server. There is no bug or failure of the plugin, even in the installation instructions it says to configure the `config.conf` file https://github.com/4drian3d/AuthMeVelocity#setup.
