### ISSUE TITLE
AUTOMATIC LOGIN WHEN TRANSFERRING TO THE LOBBY

### ISSUE THREAD

**Issue by HonzasikCZ** [4drian3d/AuthMeVelocity#92]
Hello

when I connect from one server to the lobby where AuthmeReloaded is, I have to log in

If a function could be added to automatically log in the player when switching to the lobby

**Comment by 4drian3d** [comment]
Actually AuthMeVelocity already has that function, you just have to install it as the guide says.
On each server where you have AuthMeReloaded installed, you must also install AuthMeVelocity, in addition, you must place the servers where you have AuthMeReloaded installed in the auth servers list in the AuthMeVelocity configuration
