### ISSUE TITLE
players don't get redirected if the destination server hasn't loaded fully

### ISSUE THREAD

**Issue by Serpentiel** [4drian3d/AuthMeVelocity#98]
when players login successfully, they don't get redirected to the destination server if the destination server is still loading, and they won't be redirected when the server finishes loading, so these players will have to manually use `/server xyz` to get to it

**Comment by 4drian3d** [comment]
To detect that a server is down, a more complex system is required that is completely outside the focus of AuthMeVelocity, although if one is created, using the plugin's API would suffice to make this possible

**Comment by Serpentiel** [comment]
hey, @4drian3d! 👋

have you considered implementing a workaround, such as retrying to join the server every X seconds after it was initially requested, e.g. 15 seconds?

even though imperfect, this is still going to be better for the end users, so they don't need to type `/server <name>` to join it manually
